### ISSUE TITLE
Listening to multiple teams at once?

### ISSUE THREAD

**Issue by mmattbtw** [calcom/synclinear.com#10]
I use multiple teams for 1 project/repo for things like Frontend/Backend, I'd be nice if I could listen to all of the teams in my 1 Linear organization with only 1 `linear-to-github` API running.

**Comment by PeerRich** [comment]
oh yeah that'll have to wait for a later release i guess

**Comment by PeerRich** [comment]
once the basics are up and running

**Comment by tedspare** [comment]
@mmattbtw this should now be possible. Bugs are likely, curious to hear your feedback.

**Comment by mmattbtw** [comment]
@tedspare i'm trying to set it up (through synclinear.com) however I'm not seeing my repo: `mmattDonk/AI-TTS-Donations` even though I have granted the application access.

<img width="433" alt="image" src="https://user-images.githubusercontent.com/30363562/193480356-ac73c8d1-397f-4068-9fcd-8647ac6e300d.png">

**Comment by tedspare** [comment]
Thanks for trying @mmattbtw. Are any of your (`mmattDonk/*`) repos showing up?

The app only lists the first 100 repos for now. If that's the problem, I'll add a `Show more` button.

**Comment by mmattbtw** [comment]
> Thanks for trying @mmattbtw. Are any of your `mmattDonk/*` repos showing up?
> 
> 
> 
> The app only lists the first 100 repos for now. If that's the problem, I'll add a `Show more` button.

yeah that's probably it, i have a lot of repos on my personal account

**Comment by tedspare** [comment]
@mmattbtw does it work for you now? Added a patch.

**Comment by mmattbtw** [comment]
@tedspare i could find it, and link it successfully, however I am getting this when opening an issue
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/30363562/193707484-9fd957d3-22e2-48bc-bd5c-bd1cb810ae37.png">
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/30363562/193707515-8df4abbc-4076-4b35-a647-dc5b9063bdc1.png">

**Comment by tedspare** [comment]
@mmattbtw nice, thanks for bearing with me

It looks like part of the sync wasn't saved. I've pushed a fix - could you try syncing again?

**Comment by mmattbtw** [comment]
still not working for some reason, any thoughts?

im trying to sync my "Solrock Frontend" linear team to `mmattDonk/AI-TTS-Donations` if that helps you any :p

**Comment by nikitavoloboev** [comment]
hey @tedspare 

I am trying to test this feature but I can't get to add another sync to work it does not let me add a new one.

<img width="1047" alt="image" src="https://github.com/calcom/synclinear.com/assets/6391776/c25f8091-302a-42d8-8742-c28d5945ff88">

I have Learn Anything synced. Although not as organisation, [can't find how to sync org too](https://github.com/calcom/synclinear.com/issues/127).

<img width="295" alt="image" src="https://github.com/calcom/synclinear.com/assets/6391776/c56fc22e-d56c-45ed-88f5-ab3cfe526470">

I can't add KusKus to sync too with SyncLinear. Also I can't get for orgs to show for github, it just does not show them. 😕
